/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinverse.c
 *  model: PositionControllerPan
 *  expmt: Jiwy
 *  date:  June 16, 2021
 *  time:  4:03:32 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/* No matrix support functions are needed for this model */

